baseURL = 'https://www.horgoscpa.com/'
languageCode = 'zh-tw'
title = '霍爾果斯會計師事務所'
theme = 'ananke'
paginate = 5
enableEmoji = true

[params]
  primary_color = "#2C3E50"
  secondary_color = "#E74C3C"
  accent_color = "#3498DB"
  font_main = "'Noto Sans TC', sans-serif"
  font_heading = "'Noto Sans TC', sans-serif"
  description = "專業會計解決方案｜企業成長最佳夥伴"
  featured_image = '/images/office-lg.jpg'
  logo = '/images/logo.svg'
  line_id = "@208ihted"
  address = "台中市西區建國路21號3樓之1"
  phone = "04-2220-5606"
  map_embed = "<iframe src='https://www.google.com/maps/embed?pb=...' width='600' height='450' style='border:0;' allowfullscreen='' loading='lazy'></iframe>"

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML", "AMP"]

[services]
  [[services.list]]
    icon = "fa-solid fa-calculator"
    title = "稅務規劃"
    summary = "企業稅務優化與風險管理"
  [[services.list]]
    icon = "fa-solid fa-building"
    title = "公司登記"
    summary = "一站式公司設立服務"

[menu]
  [[menu.main]]
    pre = "<i class='fa-solid fa-handshake-angle'></i>"