baseURL = "https://www.horgoscpa.com/"
languageCode = "zh-tw"
title = "霍爾果斯會計師事務所"
theme = "ananke"
DefaultContentLanguage = "zh-tw"
Paginate = 6
enableRobotsTXT = true
summaryLength = 30

[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/logo.png"
  description = "專業會計與稅務諮詢服務，幫助您解決企業財務問題"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # 自定義參數
  phone = "04-2220-5606"
  email = "contact@horgoscpa.com"
  address = "台中市西區建國路21號3樓之1"
  line_id = "@208ihted"
  form_action = "https://formspree.io/f/xwpovnwy"
  background_color_class = "bg-dark-blue"
  featured_image = "/images/hero-background.jpg"
  recent_posts_number = 3
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "services"
    name = "服務項目"
    url = "/services/"
    weight = 2
  [[menu.main]]
    identifier = "team"
    name = "專業團隊"
    url = "/team/"
    weight = 3
  [[menu.main]]
    identifier = "faq"
    name = "常見問題"
    url = "/faq/"
    weight = 4
  [[menu.main]]
    identifier = "blog"
    name = "專業文章"
    url = "/blog/"
    weight = 5
  [[menu.main]]
    identifier = "contact"
    name = "聯絡我們"
    url = "/contact/"
    weight = 6

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
