baseURL = "http://localhost:1313/"
languageCode = "zh-tw"
title = "霍爾果斯會計師事務所"
defaultContentLanguage = "zh-tw"
enableRobotsTXT = true
pagination.pagerSize = 10

[params]
  author = "霍爾果斯會計師事務所"
  description = "台中會計、記帳報稅、公司設立"
  background_color_class = "bg-black"
  recent_posts_number = 3
