baseURL = "https://www.horgoscpa.com/"
languageCode = "zh-tw"
title = "霍爾果斯會計師事務所"
theme = "ananke"
DefaultContentLanguage = "zh-tw"
Paginate = 6
enableRobotsTXT = true
summaryLength = 30

[params]
site_logo = "/images/logo.png"
favicon = "/images/favicon.ico"
description = "Your site description goes here"
featured_image = "/images/hero-background.jpg"

[menu]
[[menu.main]]
identifier = "home"
name = "首頁"
url = "/"
weight = 1

[[menu.main]]
identifier = "services"
name = "服務項目"
url = "/services/"
weight = 2

[[menu.main]]
identifier = "team"
name = "專業團隊"
url = "/team/"
weight = 3

[[menu.main]]
identifier = "faq"
name = "常見問題"
url = "/faq/"
weight = 4

[[menu.main]]
identifier = "blog"
name = "專業文章"
url = "/blog/"
weight = 5

[[menu.main]]
identifier = "contact"
name = "聯絡我們"
url = "/contact/"
weight = 6

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
