baseURL = "https://horgoscpa.com/"
languageCode = "zh-tw"
title = "霍爾果斯會計事務所"
defaultContentLanguage = "zh"

[languages]
  [languages.zh]
    languageName = "中文"
    weight = 1

# deploy trigger - force update
