# Cloudflare Workers 配置
# 宏國會計師事務所內部管理系統

name = "horgoscpa-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# ==================== Cron Jobs ====================
[triggers]
crons = [
  "0 0 1 1 *",      # 每年1月1日 00:00 - 特休年初更新
  "0 0 1 * *",      # 每月1日 00:00 - 任務生成 + 補休轉換
  "30 8 * * 1-5",   # 週一到週五 08:30 - 工時缺填提醒
  "0 2 * * *",      # 每天 02:00 - 資料庫備份
  "0 * * * *"       # 每小時 - 重試失敗的Cron Job
]

# ==================== D1 資料庫 ====================
[[d1_databases]]
binding = "DB"
database_name = "horgoscpa"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # 替換為實際 Database ID

# ==================== R2 儲存（備份+附件+外部內容）====================
[[r2_buckets]]
binding = "BACKUP"
bucket_name = "horgoscpa-backups"
preview_bucket_name = "horgoscpa-backups-preview"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "horgoscpa-attachments"
preview_bucket_name = "horgoscpa-attachments-preview"

# 外部內容儲存（Blog文章、FAQ資源、圖片）- 模組 9 & 13
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "horgoscpa-external-content"
preview_bucket_name = "horgoscpa-external-content-preview"

# ==================== KV 快取（報表快取）====================
[[kv_namespaces]]
binding = "CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # 替換為實際 KV Namespace ID
preview_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# ==================== 環境變數 ====================
[vars]
ENVIRONMENT = "production"
JWT_SECRET_KEY = "your-secret-key-here"  # ⚠️ 請替換為實際密鑰
CORS_ALLOWED_ORIGINS = "https://horgoscpa.com,https://www.horgoscpa.com"
SESSION_TIMEOUT_MINUTES = "480"  # 8小時
MAX_LOGIN_ATTEMPTS = "5"
LOGIN_LOCK_MINUTES = "15"
# R2 公開 CDN URL（外部內容使用）
CDN_BASE_URL = "https://cdn.horgoscpa.com"  # 配置 R2 自定義域名後的 CDN URL

# ==================== 開發環境 ====================
[env.development]
name = "horgoscpa-api-dev"
vars = { ENVIRONMENT = "development" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "horgoscpa-dev"
database_id = "dev-database-id"

[[env.development.r2_buckets]]
binding = "BACKUP"
bucket_name = "horgoscpa-backups-dev"

[[env.development.r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "horgoscpa-attachments-dev"

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "horgoscpa-external-content-dev"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "dev-kv-namespace-id"

# ==================== 預覽環境 ====================
[env.preview]
name = "horgoscpa-api-preview"
vars = { ENVIRONMENT = "preview" }

# ==================== 路由設定 ====================
# API路由
[[routes]]
pattern = "api.horgoscpa.com/*"
zone_name = "horgoscpa.com"

# 開發環境路由
[env.development.routes]
pattern = "api-dev.horgoscpa.com/*"
zone_name = "horgoscpa.com"

# ==================== 資源限制 ====================
[limits]
cpu_ms = 50  # CPU時間限制（毫秒）

# ==================== 構建設定 ====================
[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# ==================== 兼容性設定 ====================
# 啟用 Node.js 兼容性（使用 crypto、buffer等）
node_compat = true

