name: AI Crawler

on:
  repository_dispatch:
    types: [crawl_request]

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 獲取完整的git歷史
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run crawler
        env:
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
        run: |
          mkdir -p crawler-results
          python scripts/crawler.py "${{ github.event.client_payload.query }}" "${{ github.event.client_payload.request_id }}"
          
      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          
          # 先拉取最新變更，解決可能的衝突
          git pull origin main --rebase
          
          # 添加並提交更改
          git add crawler-results/
          git commit -m "Add search results for query: ${{ github.event.client_payload.query }}" || echo "No changes to commit"
          
          # 推送變更
          git push